# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    - go mod download

builds:
  - id: darwin
    goos:
      - darwin
    goarch:
      - amd64
  - id: linux-windows
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - 386

archives:
  - id: linux-windows
    builds:
      - linux-windows
    format: binary
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
  - id: darwin
    builds:
      - darwin
    format: binary
    name_template: "{{ .ProjectName }}-{{ .Os }}"

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  github:
    owner: aegershman
    name: cf-trueup-plugin
  draft: true
  prerelease: true
