version: "2"

tasks:
  install:
    cmds:
      - task: build
      - cf install-plugin dist/darwin_darwin_amd64/cf-usage-report-plugin -f

  uninstall:
    cmds:
      - cf uninstall-plugin cf-usage-report-plugin

  build:
    cmds:
      - go mod tidy
      - go generate ./...
      - goreleaser --snapshot --skip-publish --rm-dist
