---
version: "3"

tasks:
  build:
    cmds:
      - go mod tidy
      - go generate ./...
      - goreleaser --snapshot --skip-publish --rm-dist

  install:
    cmds:
      - task: build
      - cf install-plugin dist/darwin_darwin_amd64/cf-report-usage-plugin -f

  uninstall:
    cmds:
      - cf uninstall-plugin cf-report-usage-plugin

  test:
    cmds:
      - task: install
      - cf report-usage -o not-real-org
      - cf report-usage -o voyager --format table-org-quota # TODO on this
      - cf report-usage -o voyager -o tenzing --format string --format table --format json
      - task: uninstall
