version: "2"

tasks:
  build:
    cmds:
      - go mod tidy
      - go generate ./...
      - goreleaser --snapshot --skip-publish --rm-dist

  install:
    cmds:
      - task: build
      - cf install-plugin dist/darwin_darwin_amd64/cf-usage-report-plugin -f

  uninstall:
    cmds:
      - cf uninstall-plugin cf-usage-report-plugin

  test:
    cmds:
      - task: install
      # TODO wasteful; maybe ability to specify multiple formats on a single run...?
      - cf usage-report -o voyager -o tenzing --format string
      - cf usage-report -o voyager -o tenzing --format table
