version: "2"

tasks:
  install:
    cmds:
      - go build
      - cf install-plugin trueupreport-plugin -f

  build:
    cmds:
      - goreleaser --snapshot --skip-publish --rm-dist

  mod-init:
    cmds:
      - go mod init github.com/aegershman/cf-trueup-plugin
      - go mod tidy
