version: "2"

tasks:
  install:
    cmds:
      - task: build
      - cf install-plugin dist/cf-trueup-plugin_darwin_amd64/cf-trueup-plugin -f

  uninstall:
    cmds:
      - cf uninstall-plugin cf-trueup-plugin

  build:
    cmds:
      - go mod tidy
      - go generate ./...
      - goreleaser --snapshot --skip-publish --rm-dist
