version: "2"

tasks:
  install:
    cmds:
      - task: build
      - cf install-plugin dist/cf-trueup-plugin_darwin_amd64/cf-trueup-plugin -f

  uninstall:
    cmds:
      - cf uninstall-plugin trueup-report

  build:
    cmds:
      - goreleaser --snapshot --skip-publish --rm-dist

  mod-init:
    cmds:
      - cmd: go mod init github.com/aegershman/cf-trueup-plugin
        ignore_error: true
      - go mod tidy

  # https://git-scm.com/book/en/v2/Git-Basics-Tagging
  git-tag:
    cmds:
      - |
        version="2.5.0"
        git tag -a ${version} -m "Build version ${version}"

  # I know, not the best solution, but it'll work while I'm hacking away at stuff
  test:
    cmds:
      - cf trueup-report -o groundworks
