version: "2"

tasks:
  build:
    cmds:
      - go mod tidy
      - go generate ./...
      - goreleaser --snapshot --skip-publish --rm-dist

  install:
    cmds:
      - task: build
      - cf install-plugin dist/darwin_darwin_amd64/cf-report-usage-plugin -f

  uninstall:
    cmds:
      - cf uninstall-plugin cf-report-usage-plugin

  test:
    cmds:
      - task: install
      # TODO wasteful; maybe ability to specify multiple formats on a single run...?
      - cf report-usage -o voyager -o tenzing --format string
      - cf report-usage -o voyager -o tenzing --format table
      - cf report-usage -o voyager -o tenzing --format json
      # TODO will remove this last line, shouldn't be displayed in README
      - cf report-usage -o voyager -o tenzing --format table-org-quota
      - cf report-usage --format table-org-quota
      - cf report-usage -o not-real-org
      - task: uninstall
